use std::fmt::{Display, Formatter, Result};

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum RoomItem {
    None,
    Bombs,
    Recorder,
    BluCandle,
    RedCandle,
    Arrow,
    SilverArrow,
    Bow,
    MagicKey,
    Raft,
    Ladder,
    TriforceOfPower,
    FiveRupees,
    MagicRod,
    BookOfMagic,
    BlueRing,
    RedRing,
    PowerBracelet,
    Letter,
    Compass,
    Map,
    Rupees,
    Key,
    HeartContainer,
    Triforce,
    Boomerang,
    MagicBoomerang,
    Potion,
    Other(u8),
}

impl RoomItem {
    pub fn from_id(id: u8) -> Self {
        match id & 0x1F {
            0x00 => Self::None,
            0x03 => Self::None,
            0x05 => Self::Recorder,
            0x06 => Self::BluCandle,
            0x07 => Self::RedCandle,
            0x08 => Self::Arrow,
            0x09 => Self::SilverArrow,
            0x0A => Self::Bow,
            0x0B => Self::MagicKey,
            0x0C => Self::Raft,
            0x0D => Self::Ladder,
            0x0E => Self::TriforceOfPower,
            0x0F => Self::FiveRupees,
            0x10 => Self::MagicRod,
            0x11 => Self::BookOfMagic,
            0x12 => Self::BlueRing,
            0x13 => Self::RedRing,
            0x14 => Self::PowerBracelet,
            0x15 => Self::Letter,
            0x16 => Self::Compass,
            0x17 => Self::Map,
            0x18 => Self::Rupees,
            0x19 => Self::Key,
            0x1A => Self::HeartContainer,
            0x1B => Self::Triforce,
            0x1C => Self::Boomerang,
            0x1D => Self::MagicBoomerang,
            0x1E => Self::Potion,
            v => Self::Other(v),
        }
    }

    pub fn to_id(self) -> u8 {
        match self {
            Self::None => 0x03,
            Self::Bombs => 0x00,
            Self::Recorder => 0x05,
            Self::BluCandle => 0x06,
            Self::RedCandle => 0x07,
            Self::Arrow => 0x08,
            Self::SilverArrow => 0x09,
            Self::Bow => 0x0A,
            Self::MagicKey => 0x0B,
            Self::Raft => 0x0C,
            Self::Ladder => 0x0D,
            Self::TriforceOfPower => 0x0E,
            Self::FiveRupees => 0x0F,
            Self::MagicRod => 0x10,
            Self::BookOfMagic => 0x11,
            Self::BlueRing => 0x12,
            Self::RedRing => 0x13,
            Self::PowerBracelet => 0x14,
            Self::Letter => 0x15,
            Self::Compass => 0x16,
            Self::Map => 0x17,
            Self::Rupees => 0x18,
            Self::Key => 0x19,
            Self::HeartContainer => 0x1A,
            Self::Triforce => 0x1B,
            Self::Boomerang => 0x1C,
            Self::MagicBoomerang => 0x1D,
            Self::Potion => 0x1E,
            Self::Other(v) => v & 0x1F,
        }
    }
}

impl Display for RoomItem {
    fn fmt(&self, f: &mut Formatter<'_>) -> Result {
        write!(
            f,
            "{}",
            match self {
                Self::None => "-",
                Self::Bombs => "Bombs",
                Self::Recorder => "Recorder",
                Self::BluCandle => "Blue Candle",
                Self::RedCandle => "Red Candle",
                Self::Arrow => "Arrow",
                Self::SilverArrow => "Silver Arrow",
                Self::Bow => "Bow",
                Self::MagicKey => "Magic Key",
                Self::Raft => "Raft",
                Self::Ladder => "Ladder",
                Self::TriforceOfPower => "Triforce of Power",
                Self::FiveRupees => "5 Rupees",
                Self::MagicRod => "Magic Rod",
                Self::BookOfMagic => "Book of Magic",
                Self::BlueRing => "Blue Ring",
                Self::RedRing => "Red Ring",
                Self::PowerBracelet => "Power Bracelet",
                Self::Letter => "Letter",
                Self::Compass => "Compass",
                Self::Map => "Map",
                Self::Rupees => "Rupees",
                Self::Key => "Key",
                Self::HeartContainer => "Heart Container",
                Self::Triforce => "Triforce",
                Self::Boomerang => "Boomerang",
                Self::MagicBoomerang => "Magic Boomerang",
                Self::Potion => "Potion",
                Self::Other(_) => "?",
            }
        )
    }
}
